'use client'
import './globals.css'
import { Providers } from './providers'
// import { useSelector } from 'react-redux';
// import { GlobalState } from '@/types/types';
import Navbar from '@/components/Navbar'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const themeMode = useSelector((state: GlobalState) => state.theme.mode);
  return (
    <html lang="en" className={`light bg-gradient-to-r from-[#FAFAFA] from-10% via-[#FFEDFA] via-30% via-[#FFDCF5] via-70% via-[#A2E9C1] via-80% to-[#FDEDD3]`}>
      <body>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
